TARGET		:= Zik-Zak
SOURCES	:= .

PKG_CONFIG = arm-vita-eabi-pkg-config
SDL_LIBS := $(shell $(PKG_CONFIG) --static --libs SDL_mixer)

LIBS = -Wl,--start-group $(SDL_LIBS) -lvitaGL -lvitashark -lmathneon -lSceShaccCgExt -lSceShaccCg_stub -ltaihen_stub \
	-lvorbisfile -lvorbis -logg -lmikmod -lFLAC \
	-lpthread -lSceAudio_stub -lSceAudioIn_stub -lSceHid_stub -lz -lScePower_stub -lSceAppUtil_stub \
	-lSceAppMgr_stub -lSceCommonDialog_stub -lSceCtrl_stub -lSceGxm_stub -lSceMotion_stub -lSceNet_stub \
	-lSceTouch_stub -lSceSysmodule_stub -lSceKernelDmacMgr_stub -lSceDisplay_stub -lSceIme_stub -Wl,--end-group

CFILES   := $(foreach dir,$(SOURCES), $(wildcard $(dir)/*.c))
CPPFILES   := $(foreach dir,$(SOURCES), $(wildcard $(dir)/*.cpp))
BINFILES := $(foreach dir,$(DATA), $(wildcard $(dir)/*.bin))
OBJS     := $(addsuffix .o,$(BINFILES)) $(CFILES:.c=.o) $(CPPFILES:.cpp=.o) 

PREFIX  = arm-vita-eabi
CC      = $(PREFIX)-gcc
CXX      = $(PREFIX)-g++
CFLAGS  = -fno-lto -g -Wl,-q,--wrap,fopen,--wrap,stat,--wrap,opendir,--wrap,remove -O3 -I$(VITASDK)/$(PREFIX)/include/SDL
CXXFLAGS  = $(CFLAGS) -fno-exceptions -std=gnu++11 -fpermissive
ASFLAGS = $(CFLAGS)

all: $(TARGET).vpk

%.vpk: %.velf
	vita-mksfoex -s TITLE_ID=ZIKZAK001 -d ATTRIBUTE2=12 "Zik-Zak" param.sfo
	vita-pack-vpk -s param.sfo -b eboot.bin $@ \
		-a livearea/icon0.png=sce_sys/icon0.png \
		-a livearea/bg.png=sce_sys/livearea/contents/bg.png \
		-a livearea/startup.png=sce_sys/livearea/contents/startup.png \
		-a livearea/template.xml=sce_sys/livearea/contents/template.xml

%.velf: %.elf
	cp $< $<.unstripped.elf
	$(PREFIX)-strip -g $<
	vita-elf-create $< $@
	vita-make-fself -c -s $@ eboot.bin

$(TARGET).elf: $(OBJS)
	$(CXX) $(CXXFLAGS) $^ $(LIBS) -o $@

clean:
	@rm -rf $(TARGET).velf $(TARGET).elf $(TARGET).sysvelf $(OBJS)
